import { writeFile } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { MEMBER_ROLES } from './members.ts'
import { STAFF_ROLES } from './staff.ts'
import { ORGANISATION_ROLES } from './organisations.ts'

/**
 * The credentials table — the thing the request actually asked for.
 *
 * Everything else this feature builds exists to make these rows true.
 *
 * One row per **role**, not per account: hundreds of accounts share about a
 * dozen passwords, because one argon2 hash is computed per password and reused
 * across everyone who shares it. That is what keeps this short enough to read.
 *
 * Rows that are not meant to authenticate carry what they do instead of a
 * password. Those are the interesting accounts — a legacy credential, a locked
 * member — and a password column that lied about them would be worse than
 * leaving them out.
 */

export const CREDENTIALS = Object.freeze([...MEMBER_ROLES, ...STAFF_ROLES, ...ORGANISATION_ROLES])

/** What the password column shows where a row will not sign in. */
const NOTE = {
  password_reset_required: '(reset required)',
  refused: '(no usable password)',
  locked: '(locked)',
  inactive: '(inactive)',
  ended: '(membership ended)',
  profile_incomplete: '(email unconfirmed)',
}

export const passwordCell = (row) =>
  row.expect === 'authenticated' ? row.password : (NOTE[row.expect] ?? row.password ?? '—')

function table() {
  const rows = CREDENTIALS.map((c) => [c.kind, c.role, c.email, passwordCell(c)])
  const header = ['KIND', 'ROLE', 'EMAIL', 'PASSWORD']
  const widths = header.map((h, i) => Math.max(h.length, ...rows.map((r) => String(r[i]).length)))
  const line = (cells) => '  ' + cells.map((c, i) => String(c).padEnd(widths[i])).join('  ').trimEnd()
  return [line(header), line(widths.map((w) => '-'.repeat(w))), ...rows.map(line)].join('\n')
}

export function renderCredentials() {
  return `\n  CREDENTIALS — every role the seed created\n\n${table()}\n`
}

const HERE = dirname(fileURLToPath(import.meta.url))
const FILE = join(HERE, '..', '..', '.seed-credentials.md')

/**
 * Also written to a file, because a terminal scrolls.
 *
 * Gitignored in the same change that created it: publishing credentials on a
 * terminal is the point, committing them is not, and a file that is written
 * before it is ignored is a file that gets committed once.
 */
export async function writeCredentials() {
  const body = [
    '# Demo seed credentials',
    '',
    'Generated by `npm run -w server seed:demo`. Development only —',
    'the command refuses to run anywhere else.',
    '',
    '```',
    table(),
    '```',
    '',
    '## What each role shows',
    '',
    ...CREDENTIALS.filter((c) => c.describes).map((c) => `- **${c.role}** — ${c.describes}`),
    '',
  ].join('\n')

  await writeFile(FILE, body, 'utf8')
  return FILE
}

export const credentialFilePath = () => FILE
