// The template's web font stylesheet (src/global.css). `expo-env.d.ts`
// declares CSS imports too, but it is generated by the Expo CLI and
// gitignored, so a fresh checkout would not typecheck without this.
declare module '*.css';
